// Release history and roadmap. Rendered in-game (click the version badge) and
// mirrored in CHANGELOG.md / ROADMAP.md so the repo tells the same story.

export const VERSION = 'v1.9';

export const RELEASES = [
  {
    version: 'v1.9',
    date: '2026-09-03',
    title: 'The Cup, and a home for collectibles',
    items: [
      ['new', 'The Cup. A 32 team knockout with a new tournament every two hours and a round every twenty minutes. Back a team to win it, to reach the final, or to score the most goals; odds come from the ratings, not from the result, and stakes lock when the first round kicks off. Asked for by theasoltani-afk and by Yesman.'],
      ['new', 'Collectibles have their own tab now instead of hiding under Alternatives, and there are twelve new lots including graded cards, sealed boxes and error prints. Asked for by johnchicken.'],
      ['fix', 'Nine reports were waiting and all nine have now been read. The three sitting unanswered are upcoming films, betting on league games beyond the cup, and flipping designer fakes. They are on the list.'],
      ['bal', 'A cup result is a pure function of the tournament number, like everything else here, which means someone reading the source could work one out before backing it. Settling from a server is the honest fix and it is the same open problem as the rest of the game.'],
    ],
  },
  {
    version: 'v1.8',
    date: '2026-09-03',
    title: 'The report button actually works now',
    items: [
      ['fix', 'Reports sent while playing solo never left your device. The button said it had saved them and pointed at GitHub, which is not the same as sending them, and solo is what most people are in. Reports now go straight to the developer from solo too, over a quiet connection that never touches your save, your presence or the leaderboard.'],
      ['fix', 'Anything that got stranded on your device is sent automatically the next time you open the report box, and the box now lists your own reports with a sent or pending marker so you can see for yourself.'],
      ['fix', 'The GitHub fallback link was long enough to get truncated, which cut the attached details off the end of a real report. The browser string is gone and the details are trimmed.'],
      ['new', 'Two reports that had come in through the GitHub link have now been read and answered: a champions league investing market from theasoltani-afk, which is being built next, and the country market from Yesman, which shipped in v1.5.'],
    ],
  },
  {
    version: 'v1.7',
    date: '2026-09-03',
    title: 'Seasons, options and mortgages',
    items: [
      ['new', 'Weekly seasons. The board now ranks you on what you made since the season started, not on who has been playing longest, so joining on day six costs you nothing. Nobody loses their portfolio when a season turns over, and finished seasons stay readable from the picker.'],
      ['new', 'Options. Calls and puts on every company and fund, five strikes around the money, expiring on a shared 30 minute cycle, priced with Black-Scholes off the game rate and the tape realised volatility. You can only buy them, so the premium is the most you can lose, and they settle themselves against the price at the exact expiry tick whether you are watching or not.'],
      ['new', 'Mortgages. Finance up to 70% of a building at the policy rate plus 1.5. Your property line now shows equity rather than the whole value, and interest compounds every minute.'],
      ['new', 'Renovations. Three levels per building, 12% of the value each, and each one lifts the rent 18% permanently.'],
      ['new', 'Tenants come and go. Buildings sit empty about an eighth of the time, in stretches rather than flickering, and a vacant building earns nothing while it waits.'],
      ['bal', 'The leaderboard is rate limited on the server: at most one post every ten seconds and a cap on how far net worth can jump between posts. That makes a console-edited score hard to publish, though a patient cheat can still creep. Properly fixing it means running trades on a server, which needs a paid Firebase plan, so it stays on the roadmap rather than being quietly claimed as done.'],
      ['fix', 'A wrong approximation in the option pricing made quotes near the money collapse to a cent. Put-call parity now holds exactly.'],
      ['fix', 'A leaderboard refusal is no longer reported as a broken cloud save, because the two are different problems.'],
    ],
  },
  {
    version: 'v1.6',
    date: '2026-09-03',
    title: 'Orders and leverage',
    items: [
      ['new', 'Limit and stop orders. Set a price and walk away. Because prices here are a pure function of time, coming back replays every tick you missed and fills at the exact tick the price crossed, even if the tab was closed the whole time.'],
      ['new', 'An Orders tab showing everything working, what it is waiting for, what the price is now, and what cash is reserved against it, plus a history of fills.'],
      ['new', 'Short selling on stocks, funds, crypto and countries. You borrow the units, sell them, and buy them back later. 50% equity to open, 8% a year to borrow, and a buy-in if the position runs away from you.'],
      ['new', 'Margin loans. Borrow up to half your collateral at the policy rate plus 3.5, compounding every minute. Past 70% of collateral, positions are sold to pay it down whether you are watching or not.'],
      ['new', 'An earnings calendar. Every company reports on a schedule you can see coming, the result is fixed in advance and revealed on the day, and the next report date sits in the company window.'],
      ['new', 'Performance and leverage cards on the portfolio: return, return against the Mayhem Index, win rate, best and worst trade, debt, short exposure and borrow fees paid.'],
      ['fix', 'A forced buy-in could spend cash you did not have and leave the balance deeply negative. It now sells your longs first, covers only what the cash allows, and says so plainly if it cannot finish.'],
      ['bal', 'Orders reserve their cash while they wait, so a working order cannot be spent twice.'],
    ],
  },
  {
    version: 'v1.5',
    date: '2026-09-03',
    title: 'Countries, phones, and the first player report',
    items: [
      ['new', 'Invest in countries. 54 national economies, quoted at GDP per capita, compounding at that country growth rate and paying a yield every minute. Rich economies grow slowly and pay more; emerging ones do the opposite. Straight from a player report by Yesman: invest in every single country, and invest in their GDP per capita.'],
      ['new', 'A real phone layout. The same report came from a 384 pixel screen, so the header, the tab bar and every table now have a narrow layout instead of a squeezed desktop one. Each table keeps the three columns that matter and the tab bar scrolls.'],
      ['new', 'The portfolio now shows coupons, savings interest and sovereign yield alongside dividends, so every income stream is visible.'],
      ['fix', 'Cash could end a trade at a value like -0.0000000001, which the security rules reject, silently stopping every cloud save from then on. It is clamped now, and the status pill says "cloud save failing" if the server ever refuses a write instead of quietly pretending.'],
      ['fix', 'Going online for the first time no longer replaces your solo game with a fresh 100,000. Your solo progress comes with you.'],
      ['fix', 'A transfer could be credited twice if the delete that clears it failed. Claimed transfers are now remembered.'],
      ['fix', 'A failed sign-in left the game believing it was connected, so solo play kept trying to write to the server.'],
      ['fix', 'Two collectibles shared the ticker FIRST, which made them ambiguous when sending assets by ticker. Collectible tickers are unique now.'],
      ['fix', 'The presence heartbeat could stack up duplicate timers on a reconnect.'],
      ['fix', 'A country detail window said "undefined" where its type should be, and its chart was drawn over too short a window to show anything but noise.'],
      ['bal', 'Country shocks toned down. An economy should not move like a meme coin.'],
    ],
  },
  {
    version: 'v1.4',
    date: '2026-09-03',
    title: 'Investment Mayhem, and multiplayer is live',
    items: [
      ['new', 'The game is now called Investment Mayhem. New name in the header, the tab title and the market index; the site moved to /investment-mayhem/ and the old link redirects.'],
      ['new', 'The server is live. Press Play online and you are on the public world: shared leaderboard, live trade tape, chat, player transfers, presence, and prices that everyone nudges together.'],
      ['new', 'Bug reports filed from the game now actually reach the developer instead of only saving to your device.'],
      ['fix', 'The published security rules were rejected by Firebase because they carried "comment" keys, which are not valid rule nodes. Found while publishing them for real.'],
      ['bal', 'Version numbers now run 1.4, 1.5, 1.6 and so on up to 2.0, instead of the 1.10 / 1.20 style. Earlier builds have been relabelled to match: what shipped as v1.10 is v1.2 here, and v1.20 is v1.3.'],
      ['fix', 'A username that is already taken now says so plainly instead of reporting it as a failure to connect.'],
      ['fix', 'Saves, watchlists and cloud profiles carry across the rename untouched. The world seed is deliberately unchanged, so every property and collectible is the same one you owned before.'],
    ],
  },
  {
    version: 'v1.3',
    date: '2026-09-03',
    title: 'Bonds, savings, collectibles and bug reports',
    items: [
      ['new', 'Bonds. Eight of them, from a 2 year treasury to high yield corporate debt. Prices move against a central bank policy rate, scaled by duration, and each one pays its coupon every minute.'],
      ['new', 'A savings account. Cash parked there is never at risk and earns interest that follows the policy rate. Safe, and deliberately slower than the market.'],
      ['new', 'Collectibles. Twenty-four lots across art, watches, cards, wine and curiosities. They barely notice the stock market and sell 9% below the quoted value, because illiquidity should cost you something.'],
      ['new', 'Twelve more cryptocurrencies and ten more commodities.'],
      ['new', 'Report a bug from inside the game. Reports go to the server for the developer to read, and every report also has a one-click GitHub issue link. Fixes appear in this log.'],
      ['new', 'Live player count in the header, backed by real presence, and a join link that lets a host share their world without anyone else touching Firebase.'],
      ['fix', 'Progress is now saved after every trade, when the tab is hidden, and when it closes, instead of only every five seconds.'],
      ['fix', 'A cloud save can no longer overwrite newer local progress on refresh. Whichever is newer wins.'],
      ['fix', 'Income earned while you were away is capped at four hours. Coming back after a week no longer pays out a fortune in dividends, rent and interest.'],
      ['fix', 'Positions in an asset removed by an update are refunded at cost instead of silently vanishing. Crypto tickers changed in this release, so old holdings are paid back.'],
      ['fix', 'The watchlist, savings, bonds and collectibles are all written to the cloud save. Previously the watchlist was dropped.'],
      ['fix', 'Every module import carries the version, so a release can no longer leave a browser running a half-updated mix of cached files. This was breaking real deploys.'],
      ['fix', 'Buying a property from its detail window now updates the property table behind it, and rent can be collected straight from the portfolio.'],
      ['fix', 'Fractional orders are rejected for assets that do not support them, instead of quietly creating a third of a share.'],
    ],
  },
  {
    version: 'v1.2',
    date: '2026-09-03',
    title: 'Update log',
    items: [
      ['new', 'Click the version badge in the corner, or "what\'s new" on the login card, for the full update log and what is coming next.'],
      ['new', 'CHANGELOG.md and ROADMAP.md in the repo, generated from the same data the game reads.'],
      ['fix', 'Index funds no longer show up in the news feed as if they were a sector.'],
      ['fix', 'The trade box remembers whether you were working in shares or dollars, across assets and across reloads.'],
    ],
  },
  {
    version: 'v1.1',
    date: '2026-09-03',
    title: 'Real companies',
    items: [
      ['new', '624 real listed companies across 11 sectors replace the invented universe. Tickers and names are real; every price is simulated.'],
      ['new', 'Volatility, market beta and dividend policy are derived from each company sector and size class, so a utility behaves like a utility.'],
      ['new', '10 index funds (SPY, QQQ, DIA, IWM, VTI and sector funds) priced from their own holdings, so they genuinely track the basket.'],
      ['new', 'Watchlist stars, with Watchlist and Owned filters on the stocks table.'],
      ['new', 'Sector heat strip across the top of the stocks tab. Click a sector to filter.'],
      ['new', 'Orders can be placed in dollars instead of share counts.'],
      ['new', 'Net worth chart on the portfolio, sampled every 15 seconds against your starting bankroll.'],
      ['bal', 'Market and sector swings halved. Twenty-minute sector moves went from an absurd -35% to a believable range.'],
      ['fix', 'The price function is memoised per asset and tick, which matters now that a fund re-prices 40 members per chart frame.'],
    ],
  },
  {
    version: 'v1.0',
    date: '2026-09-03',
    title: 'First public build',
    items: [
      ['new', 'A market that nobody simulates: price is a pure function of (asset, tick), so every browser draws the identical chart with no server.'],
      ['new', 'Stocks, real estate across 7 districts, crypto, commodities and rotating angel deals.'],
      ['new', 'Firebase multiplayer: live net worth leaderboard, trade tape, chat, and cash or share transfers by username.'],
      ['new', 'Global market impact. The net units all players hold nudge the price for everyone, capped at plus or minus 22%.'],
      ['new', 'Solo mode with no backend at all, so the game runs before you own a Firebase project.'],
    ],
  },
];

// What the next update is aiming at. Ordered by what would change the game most.
export const NEXT = {
  version: 'v2.0',
  title: 'The rest of the request list',
  items: [
    ['Upcoming films',
     'Yesman asked to invest in films that have not come out yet, earning from how popular they turn out and how many tickets they sell worldwide. A slate of sequels, a budget, an opening weekend.'],
    ['League games, not just the cup',
     'Yesman again: back teams across a league season rather than only a knockout, so there is something running between tournaments.'],
    ['The counterfeit market',
     'Also Yesman: buy fakes cheap and try to sell them high, with the obvious risk that a lot turns out to be worthless.'],
    ['Price alerts',
     'Tell the game to shout when something crosses a level, instead of watching for it.'],
    ['A first run walkthrough',
     'There is a great deal in here now. A new player deserves a guided first ten minutes.'],
  ],
  later: [
    ['Server-authoritative trading and settling',
     'The honest fix for both cheating and cup results: run trades and settlements on a server so a browser cannot invent an outcome. It needs Firebase on the paid plan, so it is a decision to make rather than a thing to code.'],
    ['Bots', 'A few simulated traders so a quiet server still has a market worth beating.'],
  ],
};
